/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { House_swap } from "./House_swap";
export * as factories from "./factories";
export { House_swap__factory } from "./factories/House_swap__factory";
